### ISSUE TITLE
generate proper CSV olm-catalog file

### ISSUE THREAD

**Issue by sebgoa** [triggermesh/operator#17]
Currently:

```
$ operator-sdk olm-catalog gen-csv --csv-version 0.0.1
INFO[0000] Generating CSV manifest version 0.0.1        
INFO[0000] Fill in the following required fields in file deploy/olm-catalog/operator/0.0.1/operator.v0.0.1.clusterserviceversion.yaml:
	spec.keywords
	spec.maintainers
	spec.provider 
INFO[0000] Created deploy/olm-catalog/operator/0.0.1/operator.v0.0.1.clusterserviceversion.yaml 
```

**Comment by srueg** [comment]
Take a look at the `csv` branch.

**Comment by sebgoa** [comment]
Let's merge it so that we avoid duplicate work.

**Comment by sebgoa** [comment]
added logos and a few tidbits:

```
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[{"apiVersion":"app.triggermesh.io/v1alpha1","kind":"TriggerMesh","metadata":{"name":"example-triggermesh"},"spec":{"backend":{"baseHost":"app-test.tm.demo.vshn.net","route":{"annotations":{"kubernetes.io/tls-acme":"true"},"enabled":true}},"frontend":{"authApiId":"\u003cREDACTED\u003e","baseHost":"cloud-test.tm.demo.vshn.net","route":{"annotations":{"kubernetes.io/tls-acme":"true"},"enabled":true},"sentryDSN":"https://\u003cREDACTED\u003e@sentry.io/"},"k8sAPI":{"CA":"-----BEGIN
      CERTIFICATE-----\nMIIC6jCCAdKgAwIBAgIBATANBgkqhkiG9w0BAQsFADAmMSQwIgYDVQQDDBtvcGVu\nc2hpZnQtc2lnbmVyQDE1NTQzMDQ3MDIwHhcNMTkwNDAzMTUxODIyWhcNMjQwNDAx\nMTUxODIzWjAmMSQwIgYDVQQDDBtvcGVuc2hpZnQtc2lnbmVyQDE1NTQzMDQ3MDIw\nggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDd/NHyQyCg6a65VywMe3TT\nmuam6XK3gd3iB9vPyTXnzYTx2IEc9vRG9kYmUwu5XE7ZsOXKNaT6Xez1FPhX1FfL\nfKL9MC4n86sFRiT1zE2DfW6ycL6rJ2XaxmAe3HSw5q7FrgH9EWEC3lLPkO4Xygn+\n0T8G3sdBNbPIK8LGLjb1RBeM8Tif1AUABehCY9eb9suY+zzU1/RJ9hY5Y1X4yI4l\n5yotE3KzwL/aphiBiQGXajQLzPg7tFlE5qUuHRgo07Cqsyt9m89gVf8s3s3hfRPe\nttjA5dBnkjfaI8POJp71Nof2rXy2zaDG7QBkILrNozN1PJFH9f6+uCFKkJ8eg/Br\nAgMBAAGjIzAhMA4GA1UdDwEB/wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MA0GCSqG\nSIb3DQEBCwUAA4IBAQCkSB7BiLxBsFIm/JkyoKBupB4MB4GIqNTs+Pxwus0Z2S0U\nfW1QKh745nvNmHkXIaRyKh8dkIqIQDmUFo9FlxiS5zXxAe3F6OYmxAJ3sE24oA1m\nnoyDQ/TlaxLxLFfVo8q3fc/dIYlvyTMeFjoNb22ZClAHgXgwsxJIKhLl7J1Nux4N\nq7nCj1tBff7WGNkzN0Wj7BTMLfCcUpTYXxtRq9gmaXXxWbFLV+B4ViYg1VNJ8VSZ\n/DYgkGOKzO7Y9DFq90gVpat7+XNOGHDZtPP+IiTQZwyONxKT/b1UHJm2Q7iD23Yt\nk302uCcbAC6JcP7+lCmH/X3ZgevgeAe715kwj8Lj\n-----END
      CERTIFICATE-----\n"},"secrets":{"auth0ClientId":"\u003cREDACTED\u003e","auth0ClientSecret":"\u003cREDACTED\u003e","gitHookSecret":"\u003cREDACTED\u003e"}}}]'
    capabilities: Basic Install
  name: operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: TriggerMesh
      name: triggermeshes.app.triggermesh.io
      version: v1alpha1
      displayName: triggermesh instance
      description: Represents a running TriggerMesh instance.
  description: The TriggerMesh operator A Serverless Management Platform built on Knative
  displayName: TriggerMesh
  install:
    spec:
      deployments:
      - name: operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: operator
          strategy: {}
          template:
            metadata:
              labels:
                name: operator
            spec:
              containers:
              - env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: operator
                image: gcr.io/triggermesh/operator:latest
                imagePullPolicy: Always
                name: operator
                resources: {}
              serviceAccountName: operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - triggermesh
  - knative
  - istio
  links:
  - name: TriggerMesh
    url: https://triggermesh.com
  - name: TriggerMesh Operator Source
    url: https://github.com/triggermesh/operator
  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAALYAAAB1CAYAAADjjBseAAAAAXNSR0IArs4c6QAAActpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IlhNUCBDb3JlIDUuNC4wIj4KICAgPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KICAgICAgPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIKICAgICAgICAgICAgeG1sbnM6eG1wPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvIgogICAgICAgICAgICB4bWxuczp0aWZmPSJodHRwOi8vbnMuYWRvYmUuY29tL3RpZmYvMS4wLyI+CiAgICAgICAgIDx4bXA6Q3JlYXRvclRvb2w+QWRvYmUgSW1hZ2VSZWFkeTwveG1wOkNyZWF0b3JUb29sPgogICAgICAgICA8dGlmZjpPcmllbnRhdGlvbj4xPC90aWZmOk9yaWVudGF0aW9uPgogICAgICA8L3JkZjpEZXNjcmlwdGlvbj4KICAgPC9yZGY6UkRGPgo8L3g6eG1wbWV0YT4KKS7NPQAAFKxJREFUeAHtXc9zHEcV7pHXERQ4bFKBKkhRkarsBA4QuQpOOXjFiRNeHThbPto5WPoLHP8Fkg9WjpYPnL3mxAmvDzl7fQIsV1kcAlWQKpYYitiWd/i+bo09O9Mz293Tszu76i6tZqanf7x+803P69evXwsRQuBA4EDgQOBA4EDgQOBA4EDgQOBA4EDgQOBA4EDgQOBA4EDgQOBA4EDgQHM5EDWXtBNA2c7TtvjW0ZoYiY5Yij4QcbwiRIQfjxPDACmG+PH4VxHheOVcH+chgAMB2NOGwd6TLoB7AdV28Furofq+iMUD1NETn35I0J/IEIA9jcf++UEHfcgl9MgAtWhPo8rjOoYiinpiNLp50kAegF0XyihmvPWyK6Kl64aiRV2UHJcbHYKOm+J5a19srw5rrmzmxQdg+34EEtBHWxDyrqHoafbOpi0ZQlS5KV60dhcZ4AHYpnAwSXfr8SY+/TsNBXS2BQsN8ADs7ON2ub71eA2Avo2say7ZZ5uHIorYFlfP9mZLh9/aA7Cr8vPWwWcQOyBHz33oQf6+vCjiSQC2Kx4//9OKiFt3kX0Oe+nCRg+hvbm8CL33UmETw41iDlB9F7ceIsEigZrtbUNzclfsHXCcMNch9Ni2j08NEClPL3roQzTZmFfRJADbBp6qJ9uyyeKQto881Fg8knkjnHO6nGGUTLnjPBIf4z96WDmDiUMtYQBwr88juAOwTfHw+ZPbmDncNE1umG6IdH2Uew/HgfPsoNLKdFDGBfy6+HkM0JrEow1n2jxSYlNUALYJt/yCGj0wprljca+WQdrrGc/oGpq2ZtI8gzRD9Nyr89RzB2BPeqre1Hmy57shXpzuTQ0gcpArVZGdSc00uD9XYkkAdtkT9TJQPAb0px/ul1VV6z1/AB+Iq+fO10qrp8IDsIsYqeRWqvRcA+XnGwDCrmsB3vPtHWyhTE4mtZ3LjqJ9ceXsZef8U8oYgK1jNOXU5aOnuOUKgObO4vmYWIrjyxhM7utY15S4MEGjexLLR3cR7QLqIfRwG+ilm6v/vfLTQ6nCY8/rGmjoxRekwSEAO/twOFh00w0PRHR0vhZNR5bGqte0x6Y44Q7uNmZeb1clo878iyOKcIDEtYOlExcYyIkYP+iM4/iRWHrVF+zBkuAqVxMg35zanpq2I6HXx7GKKrPBIsl8A5vrByNxseKSqwHwcQe9LXTLDkZNczKYKn0H3MHdWP32fAJbquEasORqEUCdIH7vgOOKbnJpfIyh+fn03GfG6aeUcL6ALVd4ix2IEytT4k9xNYsEarZSaoJeQb1pzdtG9trzMXgk02WPApNKe8YXg9P1zqKBmnzggJI2IfYBi5axxrNhofnA5oBO6ZTtP5P1MBuOaZo/QeHUdPohoWhhG9TCZdtctaZvNrDVlDY+j0465ToYx8/ueh0FN6ZMKS9Te2QV2oLPqkGhucD2Yqfhm9NYNnUCfHKICDOLtiGCQ6AGhWYOHpUbMMjTjQq7mFHcbhRFdRKzd3AfxXesqoiOVsfmBawy+03c8luch9IoU4vY06zW6wkZEjbAD2XLwGP7+NzkQBHEXvY0KbmpaSLI2rElsEenOmjOfhOa1DxgK/8cNqDL8rGPCZs7uVnFbCo1y9hBND+hCeCzqdR1HM/nrKK+NWax9Ny6dzBA4nLepEuLoou43E9Hzeq8WaJINaP+PmYhbzi50i23V+5DBFmf1QOaab3245whePXOTGk+rrw5wFbmlC4akCEs6vz4wpAAp0en1CRFJNadXpYmPF0fNOwd/AvFtI2LiuPzTVgf2SCtyOnrVgxUnPZrUcfP7/NTXCGye/wgYSSFuJMcuD7TLqzZJa8ndTNkbM4sxkeblk0cSJ3y9rmhZb7y5Eqdtw297CO4APZbdnnNzbzLRcdCbBoTF0UfG6etMWEzgL3sCmpMA9cVGr5CpK5m58qls8q9A/K5nbunj1jTR083timiyCWLZsOmARMIJ2GixIIpNSftW5Rv+gJYFGmfdPbAphhio1LiAtkTvLeK/SP2kuOBRSmhx5bMWn7VsWAal//vWqQPSX1wII77PoqZZhmzl7HjeA36Z7MQwUF5CNPnAL+Qewfm9SoVYR8ZHkBs7M/iCzt7YEfS35wB0zA9fuUsmRXCbDjQR7Udw6opXnblL0KvtffkEHMDPSy/uzktW5LZA9uQU2DMTeOkIaGAuhKybsQ1oRfG2ME9IKMIIh20HTYhQscSxzY5UmnlhNcW1pRuoed3nyFOlTjpdH6APYdy3iTm13JfToOXrAeN2OsCoOxF4xEH4vtGdIxi7v7rI3SkcVXNAPdDqk1zZU9Cw5po5bg3wflEHWljbBBsmjrVtHLNonT007Gsl7O3GxNFBGVPc9+ybJPku9Jy0rP6djrAru4moXmGSEWfen6yR6MHU/WqqiwVCbq2CZI0aTg3sF46yKsP2CCHYo5fH9z1AZs9CBd5+tnIc7cxRv46QykNUhA1lH6wxUtYHKac8ujTuseqnvopCnAFdVI3bc6LfWArIzXWU1/w6IDH/wQNGU3zUy7AVdvEVWU4RcJ/18dNi5KlYxmBnjFl/VecHfYv2AGBmzApt2nFKavccfczmK2VjjhvZyNfX9f5ciaV0Bbf09pJv8Bmb7YM3xS+AJ00uAnHvYOHEqj2tLQlP+g+gi+9z6DcAncmFdn50bdF8puQtiv4DItDX4oNxfer3/EEbn+iSJ0bD83a25C7C7Dsgz62SPRgvGVgv/7ZL98V137WFu3lN/3X4bMjsf3FP0Xv6X+ztCXXPYh9G8lF4VHK9Usr+HpdQJoOfmv4+QsVxZLqwFYyHj9hXX+typU0Oxnb/6CpB1m2mhGXAvVdcKkQTDufvCe2fl78gbj8x3+I/b98nWO0jLh6zh4XxMFbL7sYV1xCGR19wZaxFRYt2DcgTZsC9X1EFTI4nbzC+ey0Ii6rtSc2FFoATjg9b+1bWSlK8EwekK+9tywe/vbHpVQMn4/E6u8OBY+5UHXVEF88gYUjlXdZA5+48MNBFVhtgmb5aBqgJt/rfnFyz1ZGKJ17R39TiJUzp8XtX/1Ayq9MY/CZPy5KDj53MFjbkTNxyWxgFA+FOILpwLEWhfUvRRiEyvZfwL1uES3p+EsfnUlfas8pnnRXvqvvtVV9fW1Gk0hF/2U4h8dKd+lHu2OSLZ8GfFo+uo54axshd2AruXNagGtLD/rJA89zoKYYTEkXBAKDvWJafl050xJ3f/1DsfGHv5fJsNkSOxhcdtCDyz8h8EjSBkeItg3ssU3CytsFjz+urDpU1avntY72bCGCAG2b0JVJswVNyZ1SHXsmAy8LWqZJmY4ioZU/M+kCeS4/z4c4wWTB8a60jF6KPkBdKyI+zZfokFFTC8qJvLa6zY/eHgN1OtHOJ9+3AXY6q5dzrXjhpWTHQmhqfOtxH/L3fZRgD25uDSKwqNoi2ANbDlzk22dRjS6pBHIPvdW9Bi+YLXwIF6BCKwrsuWcZHvztf6K7+p2JJBRqRmgk5TvQ9HXn6SpEC4KbnZRN6Eg1pMXC6iWb0mVaJTMVPnCD8gbogekuYVXOJloQa1D21JIcPns5tbpsK6K2Y1Kv3Qf4B1891xcdvfQPbNbEQSCfPb/K1sHON6AdsJXyvmNN05sM2wAz/U7sv4maz7N7xXpgDMieuTSqDxHsBkSyDXzF1gGA8zBOWpXn8pr3RA+/iaAgqNd//2UhuAlojgP0AV/SOscy7LkjMVlPniWOoi+1QobB7psZO4sgfFPLjWwMCZ5qMqmt4MAuH9jjEcCbGQ0EQcMJEMPA8cRN8aK1W6LSOjwuq/+6zEmmqUhIOqjOu/6Ld0V6MMkXsrxHn4LdO7/Stw5uAOAcUJoH6skNXahFxqUqC7KHxunfJJxPUJN+A6+vcqr6fSVvH359JHqH/ynsKd+wRJ6h5zIwF81kGrus5hJurKjji3JDKF0O1zg5B2K9NYjZrChoMge265R5xalRV755y2fr4susYn9T60qVRq2Bh8DNV89S3JlOqNE3oIWMXazTLeECF3Lul9xv/i2KCr4De2qH2TQtGVSlcU+cqoHy/TRBTXpfnOZLNLQgnTsnrJmkNwO2LEzOlpmU+SYNvZ/Oe1gSfa9NkBszebbPrrbLLieGsETs3Gde22lSGF9uW9+AEQ2vJgczYEdRZ3JR2RQcXWOQEMI4B0Yj/18A1kBwW6vS8IyocZkFqBOuKN+AydXkI911GARTYH9sUNZ4kshzTzde+vSulN2Ev/rq9GJFsY+rYJRtxaCE6J58CTiXMOvO5/mpfgmd+VuR+F4+Mh9jpu7jlLZt4KrmxQgX5qoZSnbfBc38idzCgVkDWRKV+kd607YxqVsFp0Y9thmwXexr65iWLWhpbdFyQsDMoq42GqoW3DQg69vTR3RHf8st1kwUcSlbmmC6ZGxQHjUh4Jcgaavst8hQWp4D9QF75PcNzJM+hZiIjmdKQ08OvrjiRK46gR5YTBhbxK1uaYnhphcO1AdsQyHfSyvqKESuli4cW0BNBW0C1wamP/XUA6uNmLZLSLpYcu+k3upYNHxokrY+YHuWmUwa4zVNcW/NWcNybYKcNJH2w7qHABNMLp0KQXLAwrBJpk/b6pew0BDY0Hfah7W5fYDFvbX5VDh78iIrtrjlaQrc/qE0Loedf3Qageg6i1yzDIEdH+ZymkTMozzJHkSt2Mi20BzUSU6CW02aJDHJcZL/jiTd4h8jYSeaRWJgwhRDYJsVlq8wupaPa3iM8obUzlBJC0U3lwmcNNHZcsTwemT7Gc4QNfeXbH8cd63a8U3LI7Dj+JFV5a8TY/ClrM9exzT6RNGqYzRsKWAg7xq+OYXBZFacA2/KXIq51jVP+ZQ6tW1OMnhoaDxm1mMrKyzz+sdTXp8LWVvK1UIn+9Knye54kyyv+DDoizofIJI8uZ2PPgExUuSbqE7NMAK7IhgGM2Crt8S1x8LnpnXXkJ7ZJCuzC/ZloajMd/M85JKnkwhu6S+kUJ1agIPoQcGNXLQZsJktrrRkCBqSBvZM7DW4gIKOEPWhP6an1qcxjy3iIcFNp5cnRQ0oVyaJLXPGMSXEEAt78ci4cIKAroFd/EIklUhbZJhXziJI0LRWxIi9RLQCtdH3QMYmfm389KGO1T+TVuSQRzRtrSLT61vTjFi1xPA+iCnmu45SS5txc2CzMj9r7HqVnTLqGq6LI5jjFjQzXP1j+9lDgc9b75gOVnTVa+PoTtjYgScHnPEA6bEh0lGv1tXjWmI9R7qCmmRwxb7F6nlzUYSFczW13VIe5sqGrvShXe6HOZvH/lp6q4LTdcFPngOo+ekzHIFbEWc4c6bKlHTjpcSgNm49leIcv5zzGPg8oojPw55+h1VHdsCWDzryIErggcXYGYCeTA3XsFk9SyXP7zgx8XVFjpNSr/MXnFRZakZZnOJgHTwrILdyNL+aymMtn4dLGApud2IZ7IDNwpUA37Ospyh5R77FHDhRM+Fj8ERQEwBNDVLGr0QcZ0Yx0CzdeaBSBV4y8+WTzwJfmip2Q1xMbSGCJLTbydhJLjWQ5ABgLYnydzyWK8s+2ez10lZ1SeVqgsW1Z0hKSY5D6K/fSS68Hf29eLAwPDrv8tC9tSVdkBzP0HEodzhwHNOky1PnAzyD8/noyTFuwGa5VQYCk+kqT6HTVqiBopsMV1ibZz8b/mnMO8Q3cPJT2Nxm3aAZg7P3MHtRJGk81VGsuPpgMinR/Lj0qp9LPGptIq6di09F0AMp92Xhz8QbKXqfS6ns1U/90wgT2IxIokTFfnViZ1xCHG9XUXmarnnUt5LgvvV4HTIfxZJSUOkLcImFqKKTueTeJ7G2QPquo0P2rHtf7kBA54yFXkeN1XLaavORddAYi2uoqD9eWXQTL2VnPG6OrqTOGsZjFYJ7j51USnCrJf+DJKreo0ZbIbUEepUet9O4/5v3c6AmjQS6une6mORsj1icsvxORRrTjiUzFXUz18kAPxc9FxFU7Xnwc1Id2OQW1YBKyN+tnXn0gJoNJd6BrkPsSG+nkc3Ke0xTGPz5FVkrqsOERu4CVhj0L1+/MH1zb2xLxz8e6PMD7ISQq+e2MVVNuXtKvfdxxSXegbJufhNS08fSNL72YxHRSrrO9Hl3ZfLuA/TqWhjiqK25N91noCHAImoITQocYla0okxV6BfYLJhqOPbecuUIVXchTOJA2RclnbcQ3LoXuynbdKcboD/vS7WlhYGTvpjxWP/ATsqnmSZdaEmAe+zBudlSLmjk7lya+Y+gs3lt0DknaryXAHR6xAZX9euUAdqGmkfWB+yEBglw2YNT0b6LT85hcsvpqHO3tlRcZiEYUpWXpqkyBZ6qo2wRauEmR6n8JZobsJT7Q+bCWi6mEREJoNHpKRv1Wqhyn6CpQo6a3OmgiAv48djGzzxI5zSZ5AXmoPx837/4fibx+OX6vS9FIbh9WfhxgEf7GE2gxmPSTrqlNOr5odd9auqvPwpglk5K4zvaGeMaCJgNsLMNkTYitJWWIEcPJAHPVAS8pufRzAiWTFVzT0ZqFbKyLDch2v7iK/3utIpGOsDZUKce/he8fCy5iEbeK933nBsuZWmc7ezjACQP8eME3iN5nIFteTOAjdZXDmq6+mlROdRnb/7kjEj2Z+ReiPt/foZtoku2taOGR2eTUlTJpPgJ253wxSPASSPPZ0LjpDbMyf3FATYZPgE4ls8kb4dhWUAuuY9VSOOF+qdxvPy5vap/8DhN1lCP7keHPsRsqj8RJOEBJ7JoA+En0Lrvsp+iFq+UxQI2n8/z1jr+U85zDcqqrI7VM6SImgBOG1cLisYa1GTVyGpO7sUDNgGpwL3rwOa+tHupe7Aj94tx3nhKgbpuGh2Y16QsiyVjZzmrVGy0futmb2WuBxARuDJ8PxNf76Wi7zoq6RhVxJ6eXqXq+poYETEfiRYb2MkzoMZkdKoDPeKK4MxlHLehU34kJ02asPpbAfwiyAWNOfVmH3H3IE/P/yp1NCSEwIHAgcCBwIHAgcCBwIHAgcCBwIHAgcCBwIHAgcCBwIHAgcCBwIHAgcCBwAEh/g+lrvnILbyNXAAAAABJRU5ErkJggg==
    mediatype: image/png
  maintainers:
  - email: info@appuio.ch
    name: APPUiO Team
  maturity: alpha
  provider:
    name: TriggerMesh, Inc
  version: 0.0.1

```

There is a preview at https://operatorhub.io/preview
