### ISSUE TITLE
Proper ClusterRole definition for OpenShift 4 Compatibility

### ISSUE THREAD

**Issue by tobru** [triggermesh/operator#24]
The operator wants to assign `cluster-admin` in [rbac.yaml](https://github.com/triggermesh/operator/blob/master/helm-charts/triggermesh/templates/rbac.yaml) which is - besides a very bad practice - an issue in OpenShift 4:

The operator itself runs with the ServiceAccount `triggermesh-operator` which has a ClusterRoleBinding to the ClusterRole defined in [role.yaml](https://github.com/triggermesh/operator/blob/master/deploy/role.yaml). This role has narrow permissions (great!), but this also means that this ServiceAccount isn't allowed to assign broader permissions. Currently the Helm Chart fails with:

```
user "system:serviceaccount:default:triggermesh-operator" (groups=["system:serviceaccounts" "system:serviceaccounts:default" "system:authenticated"]) is attempting to grant RBAC permissions not currently held:

{APIGroups:["*"], Resources:["*"], Verbs:["*"]}
{NonResourceURLs:["*"], Verbs:["*"]}"
```

The Chart must deliver a proper ClusterRole defining all the needed rules for Triggermesh and the ClusterRole for the operator must be updated to include these permissions.

**Comment by srueg** [comment]
@sebgoa can you create a ClusterRole which defines all the objects TriggerMesh needs to create/manage?

**Comment by sebgoa** [comment]
@tzununbekov let's check this.

I think the backend only needs to be able to create namespaces, roles and rolebinding.

**Comment by sebgoa** [comment]
@tobru how about this:

```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: triggermesh-backend
rules:
- apiGroups:
  - ""
  - apps
  - batch
  - extensions
  - tekton.dev
  - build.knative.dev
  - serving.knative.dev
  - eventing.knative.dev
  - rbac.authorization.k8s.io
  - sources.eventing.knative.dev
  - sources.eventing.triggermesh.dev
  resources:
  - serviceaccounts
  - secrets
  - routes
  - roles
  - rolebindings
  - revisions
  - configurations
  - deployments
  - builds
  - buildtemplates
  - clusterroles
  - clusterrolebindings
  - clusterbuildtemplates
  - clusterchannelprovisioners
  - channels
  - namespaces
  - services
  - subscriptions
  - tasks
  - taskruns
  - pipelines
  - pipelineruns
  - pipelineresources
  - pods
  - pods/exec
  - pods/log
  - pods/logs
  - azureeventhubsource
  - azurestorageblobsource
  - azurestoragequeuesource
  - awsdynamodbsource
  - awscodecommitsource
  - awskinesissource
  - awscognitosource
  - awsiotsource
  - awssqssource
  - awssqssources
  - containersources
  - cronjobsources
  - githubsources
  - gitlabsources
  - gcppubsubsources
  - kuberneteseventsources
  - pubsubsource
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
```
